# Generated by Django 5.1.7 on 2025-03-29 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("building", models.CharField(blank=True, max_length=100, null=True)),
                ("floor", models.CharField(blank=True, max_length=50, null=True)),
                ("room", models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="LostItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[("LOST", "Lost"), ("FOUND", "Found")],
                        default="LOST",
                        max_length=10,
                    ),
                ),
                ("category", models.CharField(max_length=100)),
                ("lost_time", models.DateTimeField(auto_now_add=True)),
                ("found_time", models.DateTimeField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="lost_items/"),
                ),
                (
                    "ai_category",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("ai_confidence", models.FloatField(blank=True, null=True)),
                (
                    "found_location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="found_items",
                        to="items.location",
                    ),
                ),
                (
                    "lost_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lost_items",
                        to="items.location",
                    ),
                ),
            ],
        ),
    ]
